### ISSUE TITLE
[Feature request] Surge3Expand 节点去重 / [BUG] Surge3ToClash 节点丢失

### ISSUE THREAD

**Issue by risin42** [0KABE/ConfConvertor#1]
通过 @Fndroid 的脚本导入了两家机场节点，代理分组中使用了机场 A 的节点 List，导出为 Surge 3 Pro 配置并生成托管，目的是与 Clash for Win / ClashA 通用配置。

使用 Surge3Expand  API 后，[Proxy] 中自动添加了被展开的节点，与 JSBox 导入的订阅节点重复，通过 Fndroid 的 surge2clash 转换后 Clash 因为节点重复报错。 

尝试使用 Surge3ToClash API 直接转换托管到 Clash，yml [Proxy] 中机场 B 节点全部丢失，机场 A 的节点同样出现重复。

在脚本中取消导入机场 A 的订阅，全部在分组中使用 List 获取节点，生成托管后使用 Surge3Expand > surge2clash 转换后，目前一切正常。

**Comment by Umshiro** [comment]
补充一个现在正常使用的托管CONF
https://c.gpu.nu/share/G3zvLeSS

**Comment by 0KABE** [comment]
Surge3Expand 更新添加了去重
SurgeToClash 等我有空了看看
